---
- name: Install GUI applications on macOS via Homebrew Cask
  hosts: localhost
  connection: local
  gather_facts: yes
  
  vars:
    gui_applications:
      - google-chrome
      - mimestream
      - figma
      - spotify
      - obsidian
      - whatsapp
      - dropbox
      - jetbrains-toolbox
      - elgato-stream-deck
      - stats
      - bitwarden
      - chatgpt
      - claude
      - 
  
  tasks:
    - name: Verify Apple Silicon architecture
      fail:
        msg: "This playbook only supports Apple Silicon Macs (arm64)"
      when: ansible_architecture != "arm64"
    
    - name: Check if Homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check
      
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not homebrew_check.stat.exists
      
    - name: Update Homebrew
      community.general.homebrew:
        update_homebrew: yes
        
    - name: Install GUI applications via Homebrew Cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ gui_applications }}"
      
    - name: Verify installed applications
      command: brew list --cask {{ item }}
      loop: "{{ gui_applications }}"
      register: app_verification
      changed_when: false
      failed_when: false
      
    - name: Display installation results
      debug:
        msg: "Successfully installed GUI applications: {{ gui_applications | join(', ') }}"