---
- name: Install applications via Mac App Store using mas
  hosts: localhost
  connection: local
  gather_facts: yes
  collections:
    - community.general.homebrew
  
  vars:
    # Apps that work better via Mac App Store
    mas_applications:
      # VPN Apps (better App Store integration)
      - id: 905953485
        name: "NordVPN"
        
      # Security & Privacy Apps
      - id: 1352778147
        name: "Bitwarden"
        
      # Productivity Apps
      - id: 1529448980
        name: "Reeder."
        
      # Creative & Design Apps  
      - id: 1024640650
        name: "CotEditor"
      - id: 1147396723
        name: "WhatsApp"        
      - id: 1444383602
        name: "GoodNotes 6"
      - id: 1287239339
        name: "ColorSlurp"
      - id: 1289583905
        name: "Pixelmator Pro"
      - id: 409203825
        name: "Numbers"   
      - id: 1295203466
        name: "Microsoft Remote Desktop"  
      - id: 1298486723
        name: "FileZilla Pro"
      - id: 411643860
        name: "DaisyDisk"        
        
  
  tasks:
    - name: Verify Apple Silicon architecture
      fail:
        msg: "This playbook only supports Apple Silicon Macs (arm64)"
      when: ansible_architecture != "arm64"
    
    - name: Check if Homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check
      
    - name: Install Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not homebrew_check.stat.exists
      
    - name: Install mas (Mac App Store CLI)
      community.general.homebrew:
        name: mas
        state: present
        
    - name: Check if signed into Mac App Store
      shell: mas account
      register: mas_account_check
      failed_when: false
      changed_when: false
      
    - name: Display Mac App Store sign-in status
      debug:
        msg: |
          {% if mas_account_check.rc == 0 %}
          ✅ Signed into App Store as: {{ mas_account_check.stdout }}
          {% else %}
          ❌ Not signed into Mac App Store
          {% endif %}
          
    - name: Show currently installed App Store apps
      shell: mas list
      register: installed_mas_apps
      changed_when: false
      when: mas_account_check.rc == 0
      
    - name: Display currently installed apps
      debug:
        msg: "Currently installed App Store apps: {{ installed_mas_apps.stdout_lines }}"
      when: mas_account_check.rc == 0
        
    - name: Install applications via Mac App Store
      shell: mas install {{ item.id }}
      loop: "{{ mas_applications }}"
      register: mas_install_result
      failed_when: false
      when: mas_account_check.rc == 0
      
    - name: Display installation results
      debug:
        msg: |
          App Store Installation Results:
          {% for item in mas_install_result.results %}
          - {{ mas_applications[loop.index0].name }}: {{ 'Success' if item.rc == 0 else 'Failed/Already Installed' }}
          {% endfor %}
      when: mas_account_check.rc == 0
      
    - name: Upgrade all App Store apps
      shell: mas upgrade
      register: mas_upgrade_result
      when: mas_account_check.rc == 0
      
    - name: Display upgrade results
      debug:
        msg: "App upgrades: {{ mas_upgrade_result.stdout_lines }}"
      when: 
        - mas_account_check.rc == 0
        - mas_upgrade_result.stdout_lines | length > 0
        
    - name: Manual sign-in instructions
      debug:
        msg: |
          📋 TO USE THIS PLAYBOOK Sign in to app store        
      when: mas_account_check.rc != 0
      
    - name: Create reference file with App Store IDs
      copy:
        content: |
          # Mac App Store Application IDs
          # Generated by Ansible on {{ ansible_date_time.date }}
          
          {% for app in mas_applications %}
          {{ app.id }} - {{ app.name }}
          {% endfor %}
          
          # Search results:
          {% if app_search_results is defined %}
          {% for item in app_search_results.results %}
          # {{ item.item }}: {{ item.stdout_lines[0] if item.stdout_lines else 'Not found' }}
          {% endfor %}
          {% endif %}
          
          # Useful commands:
          # mas list                    # Show installed apps
          # mas search "AppName"        # Find App Store ID
          # mas install <ID>            # Install app
          # mas uninstall <ID>          # Remove app  
          # mas upgrade                 # Update all apps
        dest: ~/mas_app_reference.txt
        
    - name: Final summary
      debug:
        msg: |
          🎉 Mac App Store Apps Management Complete!
          
          {% if mas_account_check.rc == 0 %}
          ✅ {{ mas_applications | length }} apps processed via App Store
          ✅ All apps updated to latest versions
          ✅ Reference file created: ~/mas_app_reference.txt
          {% else %}
          ⚠️  Sign into App Store first, then re-run playbook
          {% endif %}
          
          💡 Why these apps use App Store:
          - VPNs: Better network extension integration
          - Security apps: Proper entitlements and sandboxing  
          - Apple apps: Official distribution and updates
          - Note apps: iCloud sync and advanced features
          - Utilities: System-level permissions