---
- import_playbook: install.tools.ansible-play.yml
- import_playbook: install.gui.ansible-play.yml
- import_playbook: install.mas.ansible-play.yml
- import_playbook: install.xcode.ansible-play.yml
- import_playbook: install.adjust.ansible-play.yml
